version: "3.7"
services:
  postgres:
    container_name: the-resident-zombie
    image: postgres:12
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=trz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PG_DATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./config/container/db-scripts:/docker-entrypoint-initdb.d
volumes:
  postgres: